pipeline {
    agent { //https://www.jenkins.io/doc/book/pipeline/syntax/#agent
        node {
            label 'boo'
        }
    }
    stages {
        stage('Test') {
            steps {
                dir('003_ci/powershell'){
                    pwsh "Invoke-Pester -Path .\\app.Tests.ps1"
                }
            }
        }
        stage('Import') {
            steps {
                dir('003_ci/powershell'){
                        pwsh '. .\\app.Tests.ps1'
                }
            }
        }
        stage('Run') {
            steps {
                dir('003_ci/powershell'){
                       pwsh 'Select-Winner -Team1 "Legia" -Team2 "Karabach Agdam"'
                }
            }
        }

    }
}